-- Create the SH schema
CREATE SCHEMA SH;

-- Use the SH schema
USE SH;

-- Create tables
CREATE TABLE SH.COUNTRIES (
    COUNTRY_ID INT PRIMARY KEY,
    COUNTRY_ISO_CODE CHAR(2),
    COUNTRY_NAME VARCHAR(255)
);

CREATE TABLE SH.PRODUCTS (
    PROD_ID INT PRIMARY KEY,
    PROD_NAME VARCHAR(255),
    PROD_DESC VARCHAR(255),
    PROD_SUBCATEGORY VARCHAR(255),
    PROD_SUBCATEGORY_DESC VARCHAR(255),
    PROD_CATEGORY VARCHAR(255),
    PROD_CATEGORY_DESC VARCHAR(255)
);

CREATE TABLE SH.CHANNELS (
    CHANNEL_ID INT PRIMARY KEY,
    CHANNEL_DESC VARCHAR(255)
);

CREATE TABLE SH.TIMES (
    TIME_ID DATE PRIMARY KEY,
    DAY_NUMBER INT,
    WEEK_DAY VARCHAR(10),
    MONTH_NUMBER INT,
    MONTH_DESC VARCHAR(10),
    QUARTER VARCHAR(10),
    YEAR INT
);

CREATE TABLE SH.CUSTOMERS (
    CUST_ID INT PRIMARY KEY,
    CUST_FIRST_NAME VARCHAR(255),
    CUST_LAST_NAME VARCHAR(255),
    CUST_GENDER CHAR(1),
    CUST_YEAR_OF_BIRTH INT,
    CUST_MARITAL_STATUS VARCHAR(255),
    COUNTRY_ID INT,
    FOREIGN KEY (COUNTRY_ID) REFERENCES SH.COUNTRIES(COUNTRY_ID)
);

CREATE TABLE SH.PROMOTIONS (
    PROMO_ID INT PRIMARY KEY,
    PROMO_NAME VARCHAR(255),
    PROMO_DESC VARCHAR(255),
    PROMO_CATEGORY VARCHAR(255)
);

CREATE TABLE SH.DIMENSION_EXCEPTIONS (
    DIM_ID INT PRIMARY KEY,
    DIM_ATTRIBUTE VARCHAR(255),
    DIM_VALUE VARCHAR(255),
    EXCEPTION_DESCRIPTION VARCHAR(255)
);

CREATE TABLE SH.SUPPLEMENTARY_DEMOGRAPHICS (
    CUST_ID INT PRIMARY KEY,
    EDUCATION VARCHAR(255),
    OCCUPATION VARCHAR(255),
    HOUSEHOLD_SIZE VARCHAR(255),
    YRS_RESIDENCE INT
);

CREATE TABLE SH.SALES (
    PROD_ID INT,
    CUST_ID INT,
    TIME_ID DATE,
    CHANNEL_ID INT,
    PROMO_ID INT,
    QUANTITY_SOLD INT,
    AMOUNT_SOLD DECIMAL(10, 2),
    FOREIGN KEY (PROD_ID) REFERENCES SH.PRODUCTS(PROD_ID),
    FOREIGN KEY (CUST_ID) REFERENCES SH.CUSTOMERS(CUST_ID),
    FOREIGN KEY (TIME_ID) REFERENCES SH.TIMES(TIME_ID),
    FOREIGN KEY (CHANNEL_ID) REFERENCES SH.CHANNELS(CHANNEL_ID),
    FOREIGN KEY (PROMO_ID) REFERENCES SH.PROMOTIONS(PROMO_ID)
);

CREATE TABLE SH.COSTS (
    PROD_ID INT,
    TIME_ID DATE,
    UNIT_COST DECIMAL(10, 2),
    FOREIGN KEY (PROD_ID) REFERENCES SH.PRODUCTS(PROD_ID),
    FOREIGN KEY (TIME_ID) REFERENCES SH.TIMES(TIME_ID)
);

CREATE TABLE SH.PROFITS (
    PROD_ID INT,
    CHANNEL_ID INT,
    TIME_ID DATE,
    PROFIT DECIMAL(10, 2),
    FOREIGN KEY (PROD_ID) REFERENCES SH.PRODUCTS(PROD_ID),
    FOREIGN KEY (CHANNEL_ID) REFERENCES SH.CHANNELS(CHANNEL_ID),
    FOREIGN KEY (TIME_ID) REFERENCES SH.TIMES(TIME_ID)
);

CREATE TABLE SH.FWEEK_PSCAT_SALES_MV (
    TIME_ID DATE PRIMARY KEY,
    PROD_SUBCATEGORY VARCHAR(255),
    CHANNEL_DESC VARCHAR(255),
    AMOUNT_SOLD DECIMAL(10, 2)
);

CREATE TABLE SH.CAL_MONTH_SALES_MV (
    TIME_ID DATE PRIMARY KEY,
    CHANNEL_DESC VARCHAR(255),
    PROD_CATEGORY_DESC VARCHAR(255),
    AMOUNT_SOLD DECIMAL(10, 2)
);

-- Add foreign key constraints with ALTER TABLE

-- For example, you can add foreign key constraints here as needed

-- For example, for the "SALES" table
ALTER TABLE SH.SALES
ADD CONSTRAINT FK_PROD_ID FOREIGN KEY (PROD_ID) REFERENCES SH.PRODUCTS(PROD_ID);

ALTER TABLE SH.SALES
ADD CONSTRAINT FK_CUST_ID FOREIGN KEY (CUST_ID) REFERENCES SH.CUSTOMERS(CUST_ID);

ALTER TABLE SH.SALES
ADD CONSTRAINT FK_TIME_ID FOREIGN KEY (TIME_ID) REFERENCES SH.TIMES(TIME_ID);

ALTER TABLE SH.SALES
ADD CONSTRAINT FK_CHANNEL_ID FOREIGN KEY (CHANNEL_ID) REFERENCES SH.CHANNELS(CHANNEL_ID);

ALTER TABLE SH.SALES
ADD CONSTRAINT FK_PROMO_ID FOREIGN KEY (PROMO_ID) REFERENCES SH.PROMOTIONS(PROMO_ID);