CREATE SCHEMA `olym` ;

-- Create OLYM_ATHLETES table
CREATE TABLE olym.OLYM_ATHLETES (
    ID INT PRIMARY KEY,
    ATHLETE_NAME VARCHAR(255) UNIQUE,
    ATHLETE_GENDER VARCHAR(255)
);

-- Create OLYM_ATHLETE_GAMES table
CREATE TABLE olym.OLYM_ATHLETE_GAMES (
    ID INT PRIMARY KEY,
    ATHLETE_ID INT UNIQUE,
    GAME_ID INT UNIQUE,
    NATION_ID INT UNIQUE
);

-- Create OLYM_BASE_EVENTS table
CREATE TABLE olym.OLYM_BASE_EVENTS (
    ID INT PRIMARY KEY,
    DISCIPLINE_ID INT UNIQUE,
    EVENT VARCHAR(255) UNIQUE
);

-- Create OLYM_DISCIPLINES table
CREATE TABLE olym.OLYM_DISCIPLINES (
    ID INT PRIMARY KEY,
    SPORT_ID INT UNIQUE,
    DISCIPLINE VARCHAR(255)
);

-- Create OLYM_EVENTS table
CREATE TABLE olym.OLYM_EVENTS (
    ID INT PRIMARY KEY,
    BASE_EVENT_ID INT UNIQUE,
    EVENT_GENDER VARCHAR(255) UNIQUE
);

-- Create OLYM_GAMES table
CREATE TABLE olym.OLYM_GAMES (
    ID INT PRIMARY KEY,
    YEAR INT UNIQUE,
    SEASON VARCHAR(255) UNIQUE,
    CITY VARCHAR(255)
);

-- Create OLYM_MEDALS table
CREATE TABLE olym.OLYM_MEDALS (
    ID INT PRIMARY KEY,
    EVENT_ID INT,
    ATHLETE_GAME_ID INT,
    MEDAL VARCHAR(255)
);

-- Create OLYM_NATIONS table
CREATE TABLE olym.OLYM_NATIONS (
    ID INT PRIMARY KEY,
    NATION VARCHAR(255) UNIQUE
);

-- Create OLYM_SPORTS table
CREATE TABLE olym.OLYM_SPORTS (
    ID INT PRIMARY KEY,
    SPORT VARCHAR(255) UNIQUE
);

-- Add foreign key constraints

-- Foreign keys for OLYM_ATHLETE_GAMES table
ALTER TABLE olym.OLYM_ATHLETE_GAMES
ADD CONSTRAINT FK_ATHLETE_ID
FOREIGN KEY (ATHLETE_ID) REFERENCES OLYM_ATHLETES(ID);

ALTER TABLE olym.OLYM_ATHLETE_GAMES
ADD CONSTRAINT FK_GAME_ID
FOREIGN KEY (GAME_ID) REFERENCES OLYM_GAMES(ID);

ALTER TABLE olym.OLYM_ATHLETE_GAMES
ADD CONSTRAINT FK_NATION_ID
FOREIGN KEY (NATION_ID) REFERENCES OLYM_NATIONS(ID);

-- Foreign keys for OLYM_DISCIPLINES table
ALTER TABLE olym.OLYM_DISCIPLINES
ADD CONSTRAINT FK_SPORT_ID
FOREIGN KEY (SPORT_ID) REFERENCES OLYM_SPORTS(ID);

-- Foreign keys for OLYM_EVENTS table
ALTER TABLE olym.OLYM_EVENTS
ADD CONSTRAINT FK_BASE_EVENT_ID
FOREIGN KEY (BASE_EVENT_ID) REFERENCES OLYM_BASE_EVENTS(ID);

-- Foreign keys for OLYM_MEDALS table
ALTER TABLE olym.OLYM_MEDALS
ADD CONSTRAINT FK_EVENT_ID
FOREIGN KEY (EVENT_ID) REFERENCES OLYM_EVENTS(ID);

ALTER TABLE olym.OLYM_MEDALS
ADD CONSTRAINT FK_ATHLETE_GAME_ID
FOREIGN KEY (ATHLETE_GAME_ID) REFERENCES OLYM_ATHLETE_GAMES(ID);
